version: 2.0.1.{build}
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
  project_feed: true
before_build:
- cd Source
- nuget restore
- cd ..
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal